apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: oteld
spec:
  mode: daemonset
  hostNetwork: true
  serviceAccount: otelcontribcol
  image: otel/opentelemetry-collector-contrib:0.61.0
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      zipkin:
        endpoint: 0.0.0.0:9411

      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: "localhost:65535"


    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800

      groupbytrace:
        wait_duration: 30s
        num_traces: 1000

      spanmetrics:
        metrics_exporter: dynatrace

      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 30


      tail_sampling:
        decision_wait: 5s
        policies:
          - name: tracetest-spans
            type: trace_state
            trace_state: { key: tracetest, values: ["true"] }

      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        filter:
          node_from_env_var: K8S_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time

    exporters:
      logging:


      otlphttp:
        endpoint: DT_URL_TO_REPLACE/api/v2/otlp
        headers:
          Authorization: "Api-Token DT_TOKEN_TO_REPLACE"

      otlp/1:
        endpoint: http://tracetest.tracetest.svc.cluster.local:21321
        tls:
          insecure: true


      otlp/spanmetrics:
          endpoint: "localhost:55677"
          tls:
            insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter,k8sattributes,tail_sampling,spanmetrics,batch]
          exporters: [otlphttp,otlp/1]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,k8sattributes,batch]
          exporters: [otlphttp]
        metrics/spanmetrics:
          receivers: [otlp/spanmetrics]
          exporters: [otlp/spanmetrics]