apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-tracetest-check
spec:
  runInterval: 30s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  podSpec: # The exact pod spec that will run.  All normal pod spec is valid here.
    containers:
      - env: # Environment variables are optional but a recommended way to configure check behavior
          - name: TRACETEST_URL
            value: "http://tracetest.tracetest.svc:11633"
        volumeMounts:
          - name: test-volume
            mountPath: /test
        image: hrexed/tracetest-kuberhealthycheck:0.1 # The image of the check you just pushed
        imagePullPolicy: Always # During check development, it helps to set this to 'Always' to prevent on-node image caching.
        name: tracetestcheck
    volumes:
      - name: test-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: tracetest-config
